"""Alter Generic to VARCHAR(255)

Revision ID: 44b899867436
Revises: 10ce68c7da4d
Create Date: 2025-07-28 22:19:54.874652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '44b899867436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_formulary_feb_2025', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('va_formulary_feb_2025', 'Generic',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'VA Class',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Restriction',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Dosage Form',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Comments',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'U/E Formulary',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Clinical Guidance',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_generic_prefix'), table_name='va_formulary_feb_2025', mysql_length={'Generic': 100})
    op.create_index(op.f('ix_va_formulary_feb_2025_Generic'), 'va_formulary_feb_2025', ['Generic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_va_formulary_feb_2025_Generic'), table_name='va_formulary_feb_2025')
    op.create_index(op.f('idx_generic_prefix'), 'va_formulary_feb_2025', ['Generic'], unique=False, mysql_length={'Generic': 100})
    op.alter_column('va_formulary_feb_2025', 'Clinical Guidance',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'U/E Formulary',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Comments',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Dosage Form',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Restriction',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'VA Class',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('va_formulary_feb_2025', 'Generic',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('va_formulary_feb_2025', 'id')
    # ### end Alembic commands ###
